[package]
name = "nano-sync"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Recursive SNARKs for Nimiq's Nano Nodes"
license = "MIT/Apache-2.0"
repository = "https://github.com/nimiq/nano-sync"
edition = "2018"

[dependencies]
blake2-rfc = "0.2"
byteorder = "1.3.4"
colored = { version = "1.9", optional = true }
hex = "0.4"
rand = "0.7"

algebra = { git = "https://github.com/nimiq/zexe.git", branch = "nimiq", features = ["mnt4_753", "mnt6_753"] }
algebra-core = { git = "https://github.com/nimiq/zexe.git", branch = "nimiq"}
crypto-primitives = { git = "https://github.com/nimiq/zexe.git", branch = "nimiq", features = ["r1cs", "groth16"] }
groth16 = { git = "https://github.com/nimiq/zexe.git", branch = "nimiq", features = ["parallel"] }
r1cs-core = { git = "https://github.com/nimiq/zexe.git", branch = "nimiq" }
r1cs-std = { git = "https://github.com/nimiq/zexe.git", branch = "nimiq", features = ["mnt4_753", "mnt6_753"] }

[features]
default = []
cost-analysis = ["colored"]
print-trace = ["groth16/print-trace"]