[package]
name = "nimiq-bls"
version = "0.1.0"
authors = ["Jack Grigg <str4d@i2pmail.org>", "The Nimiq Core Development Team <info@nimiq.com>"]
description = "BLS signatures"
license = "MIT/Apache-2.0"
repository = "https://github.com/nimiq/bls"
edition = "2018"

[dependencies]
blake2-rfc = "0.2"
byteorder = "1.3.4"
failure = "0.1"
hex = "0.4"
log = "0.4"
num-traits = { version = "0.2", default-features = false }
parking_lot = { version = "0.9", optional = true }
rand = "0.7"
rand_chacha = "0.2"

algebra = { git = "https://github.com/nimiq/zexe", branch = "nimiq", features=["mnt6_753"]}
algebra-core = { git = "https://github.com/nimiq/zexe", branch = "nimiq"}
crypto-primitives = { git = "https://github.com/nimiq/zexe", branch = "nimiq"}

beserial = { path = "../beserial", version = "0.1", optional = true }
nano-sync = { path = "../nano-sync", version = "0.1" }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1", features = ["key-rng"] }

[dev-dependencies]
rand_xorshift = "0.2"

[features]
default = ["beserial", "lazy"]
lazy = ["parking_lot"]
