[package]
name = "nimiq-tools"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Tools for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[[bin]]
name = "nimiq-bls"
path = "src/bls/main.rs"

[[bin]]
name = "nimiq-address"
path = "src/address/main.rs"

[[bin]]
name = "nimiq-signtx"
path = "src/signtx/main.rs"

[dependencies]
clap = "2.33"
failure = "0.1"
hex = "0.4"
log = "0.4"
rand = "0.7"
simple_logger = "1.0"

beserial = { path = "../beserial", version = "0.1" }
nimiq-bls = { path = "../bls", version = "0.1" }
nimiq-build-tools = { path = "../build-tools", version = "0.1" }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-keys = { path = "../keys", version = "0.1" }
nimiq-primitives = { path = "../primitives", version = "0.1" }
nimiq-transaction = { path = "../primitives/transaction", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1" }
